crystal:
	crystal build -Dpreview_mt --release crystal_server.cr
	./crystal_server

node:
	node node_server.js

rust:
	cd hyper_server; cargo run --release

jennet:
	./jennet-master/build/release/params
